name: Code Linting

on:
  push:
    branches:
      - "feature/**"
      - "main"

jobs:
  Linting_Check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
